version: "3.8"

services:
    nats:
        image: nats:latest
        command: []
        ports:
            - "4222:4222"
            - "6222:6222"
<<<<<<< HEAD
            - "8222:8222"
=======
            - "8222:8222"
>>>>>>> 42bd07682392cefdf8f368a2987a00a7611a91b0
