#! /usr/bin/env bash

function start() {
    docker-compose up
}

function stop() {
    docker-compose stop
}

function docker-build() {
    docker build . -t jwalab/airlock
}

function docker-push() {
    docker push jwalab/airlock
}

"$@"